### ISSUE TITLE
Feature Request: Channel Sample Selection

### ISSUE THREAD

**Issue by JohannesMP** [MatthewCech/ASCIIPlayer#7]
Currently Visualizer data is only grabbed from the left channel.

This is apparent when playing back a channel test track, for example: http://www.careysound.com/oldsite/downloads/audiofiles/files/Track%201.aiff

It makes sense for performance reasons to not just automatically average data from the left and right channel, but it would be potentially useful to allow users to see which channel is selected and the ability to switch between left, right and both (averaged).

A `Visualizer Channel Source` setting should be added with options:
- Left (Default)
- Right
- Average

This setting should be visible in the 'Debug' UI as well as any visualizers where it makes sense, such as any that are intended for audio analysis.

A key for cycling channel source mode would also be useful. audio analysis visualizers would display text such as "Channel displayed: Left   | Press Z to cycle"

**Comment by MatthewCech** [comment]
Resolved with new stereo visualization style in v0.3.1!
